In [7]:
import os
import pandas as pd
import glob

In [8]:
# Merging all csv files 
dfs = glob.glob("*.csv")
df_merged = pd.concat((pd.read_csv(f, header = 0) for f in dfs))
df_merged

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,330,2019-06-01 00:00:01.5000,2019-06-01 00:05:31.7600,3602.0,31 Ave & 34 St,40.763154,-73.920827,3570.0,35 Ave & 37 St,40.755733,-73.923661,20348,Subscriber,1992,1
1,830,2019-06-01 00:00:04.2400,2019-06-01 00:13:55.1470,3054.0,Greene Ave & Throop Ave,40.689493,-73.942061,3781.0,Greene Av & Myrtle Av,40.698568,-73.918877,34007,Subscriber,1987,2
2,380,2019-06-01 00:00:06.0190,2019-06-01 00:06:26.7790,229.0,Great Jones St,40.727434,-73.993790,326.0,E 11 St & 1 Ave,40.729538,-73.984267,20587,Subscriber,1990,2
3,1155,2019-06-01 00:00:06.7760,2019-06-01 00:19:22.5380,3771.0,McKibbin St & Bogart St,40.706237,-73.933871,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,33762,Subscriber,1987,1
4,1055,2019-06-01 00:00:07.5200,2019-06-01 00:17:42.5580,441.0,E 52 St & 2 Ave,40.756014,-73.967416,3159.0,W 67 St & Broadway,40.774925,-73.982666,31290,Subscriber,1973,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2329509,1562,2020-08-31 23:59:29.7690,2020-09-01 00:25:31.9660,298.0,3 Ave & Schermerhorn St,40.686832,-73.979677,3423.0,West Drive & Prospect Park West,40.661063,-73.979453,37282,Customer,2001,1
2329510,1023,2020-08-31 23:59:32.1320,2020-09-01 00:16:35.3710,3508.0,St Nicholas Ave & Manhattan Ave,40.809725,-73.953149,3323.0,W 106 St & Central Park West,40.798186,-73.960591,35088,Customer,1993,2
2329511,600,2020-08-31 23:59:33.0920,2020-09-01 00:09:33.4670,320.0,Leonard St & Church St,40.717571,-74.005549,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,36353,Subscriber,2002,1
2329512,737,2020-08-31 23:59:35.7900,2020-09-01 00:11:53.2310,3318.0,2 Ave & E 96 St,40.783964,-73.947167,3156.0,E 72 St & York Ave,40.766638,-73.953483,44935,Subscriber,1981,2
2329513,373,2020-08-31 23:59:45.3470,2020-09-01 00:05:59.1630,3423.0,West Drive & Prospect Park West,40.661063,-73.979453,3398.0,Smith St & 9 St,40.674696,-73.997858,38938,Customer,1969,0

In [11]:
# Export merged file as a csv file
df_merged.to_csv("citibike_tripdata_merged.csv")